name: Update Coverage
on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 15
      - name: Install dependencies
        run: npm install
      - name: run tests
        run: npm run test
      - name: update readme
        run: npx update-badge